config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :discussions do
   resources :comments
  end

  root to: 'discussions#index'
 # resources :discussions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
  belongs_to :user
end

app/models/discussion.rb
class Discussion < ApplicationRecord

 validates :headline, presence: true

 belongs_to :user
 has_many :comments


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 has_many :discussions
 has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
      protect_from_forgery with: :exception

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
      before_action :authenticate_user!, except: [:index, :show]
    
    def create
      @discussion = Discussion.find(params[:discussion_id])
      @comment = @discussion.comments.create(params[:comment].permit(:comment, :url_image))

      @comment.user_id = current_user.id if current_user
      @comment.save
      
      if @comment.save
        redirect_to discussion_path(@discussion)
      else
       render 'new'
      end
    end
    
    def destroy
      @discussion = Discussion.find(params[:discussion_id])
      @comment = @discussion.comments.find(params[:id])
      
      @comment.destroy
      redirect_to discussion_path(@discussion)
    end
    
    
    def edit
      @discussion = Discussion.find(params[:discussion_id])
      @comment = @discussion.comments.find(params[:id])
    end
    
    def update
      @discussion = Discussion.find(params[:discussion_id])
      @comment = @discussion.comments.find(params[:id])
      
      if @comment.update(params[:comment].permit(:comment, :url_image))
         redirect_to discussion_path(@discussion)
      else
       render 'edit'
      end
    end
    
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  
  before_action :find_discussion, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /discussions
  # GET /discussions.json
  def index
    @discussions = Discussion.all.order ("created_at DESC")
  end

  # GET /discussions/1
  # GET /discussions/1.json
  def show
      @discussion = Discussion.find(params[:id])
  end

  # GET /discussions/new
  def new
    @discussion = current_user.discussions.build
  end

  # GET /discussions/1/edit
  def edit
  end

  # POST /discussions
  # POST /discussions.json
  def create
    
    @discussion = current_user.discussions.build(discussion_params)

    respond_to do |format|
      if @discussion.save
        format.html { redirect_to @discussion, notice: "Post Criado com Sucesso." }
        format.json { render :show, status: :created, location: @discussion }
      else
        format.html { render :new, alert: "Não foi possível Salvar as informações." }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discussions/1
  # PATCH/PUT /discussions/1.json
  def update
    respond_to do |format|
      if @discussion.update(discussion_params)
        format.html { redirect_to @discussion, notice: "Post Alterado com Sucesso."}
        format.json { render :show, status: :ok, location: @discussion }
      else
        format.html { render :edit, alert: "Não foi possível Salvar as informações." }
        format.json { render json: @discussion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discussions/1
  # DELETE /discussions/1.json
  def destroy
    @discussion.destroy
    respond_to do |format|
      format.html { redirect_to discussions_url, notice: 'Post Deletado com Sucesso' }
      format.json { head :no_content }
    end
  end

  private
    
    def find_discussion
     @discussion = Discussion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discussion_params
      params.require(:discussion).permit(:headline, :content, :user_id, :url_image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

    
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/views/comments/_comment.html.erb
<div class='comment'>
   
<br>
<br>
   
<div class="col s12 m7">
    <div class="card horizontal">
     
        <% if comment.url_image? %>
         <img <%= image_tag comment.url_image, width:80, heidth:80 %>
        <% end %>
      
      <div class="card-stacked">
        <div class="card-content">
        <p> <%= comment.comment %> </p>
        </div>
      </div>
</div>
    <label class="green-text text-darken-2"><p> <%= comment.user.email %> </p></label>


    
    <td><%= link_to 'Editar Resposta',  edit_discussion_comment_path(comment.discussion, comment) %> </td> | 
    <td><%= link_to 'Deletar Resposta',  [comment.discussion, comment], method: :delete, data: { confirm: ' Tem certeza ?' } %> </td>
       
</div>

app/views/comments/_form.html.erb
<%= form_with(model: [ @discussion, @discussion.comments.build ], local: true) do |form| %>
   
   <div class="field">
    <%= form.label "Conteúdo: " %>
     <p class="emoji-picker-container">
      <%= form.text_area :comment, cols: "30", rows: "10", data: { emojiable: true } %>
     </p>
  </div>
   <div class="field">
    <%= form.label "Imagem: " %>
      <%= form.text_field :url_image%>
  </div>
  
   <div class="actions">
    <%= form.submit "Salvar", class: "waves-effect waves-light btn" %>
  </div>
  
<% end %>

app/views/comments/edit.html.erb
<h4>Editar Comentário</h4>

<%= form_with(model: [ @discussion, @comment ], local: true) do |form| %>
   
   <div class="field">
    <%= form.label "Conteúdo: " %>
     <p class="emoji-picker-container">
      <%= form.text_area :comment, cols: "30", rows: "10", data: { emojiable: true } %>
     </p>
  </div>
   <div class="field">
    <%= form.label "Imagem: " %>
      <%= form.text_field :url_image%>
  </div>
  
   <div class="actions">
    <%= form.submit "Atualizar", class: "waves-effect waves-light btn" %>
  </div>
  
<% end %>

app/views/discussions/_form.html.erb
<%= form_with(model: discussion, local: true) do |form| %>
  <% if discussion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(discussion.errors.count, "error") %> prohibited this discussion from being saved:</h2>

      <ul>
      <% discussion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Título: " %>
     <%= form.text_field :headline %>
  </div>

  <div class="field">
    <%= form.label "Conteúdo: " %>
     <p class="emoji-picker-container">
      <%= form.text_area :content, cols: "30", rows: "10", data: { emojiable: true } %>
     </p>
  </div>
  
   <div class="field">
    <%= form.label "Imagem: " %>
      <%= form.text_field :url_image%>
   </div>

  <div class="actions">
    <%= form.submit "Salvar", class: "waves-effect waves-light btn" %>
  </div>
<% end %>

app/views/discussions/edit.html.erb
<h4>Editing Discussion</h4>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Mostrar', @discussion , class: "waves-effect waves-teal btn-flat" %> |
<%= link_to 'Voltar', discussions_path, class: "waves-effect waves-teal btn-flat" %>

app/views/discussions/index.html.erb
<h4>Discusões</h4>

<table class="striped">
  <thead>
    <tr>
      <th>Título</th>
    <!--  <th>Conteúdo</th>-->
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @discussions.each do |discussion| %>
      <tr>
        <td><%= discussion.headline %></td>
     <!--   <td><%= discussion.content %></td> -->
        <td><%= "Publicado à " + time_ago_in_words(discussion.created_at) +" por " %><span class="blue-text blue lighten-5"><%= discussion.user.email %></span></td>
        <td><%= link_to 'Mostrar', discussion %></td>
        <td><%= link_to 'Editar', edit_discussion_path(discussion) %></td>
        <td><%= link_to 'Deletar', discussion, method: :delete, data: { confirm: ' Tem certeza ?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Post', new_discussion_path, class: "waves-effect waves-light btn" %>

app/views/discussions/new.html.erb
<h4>Novo Post</h4>

<%= render 'form', discussion: @discussion %>

<%= link_to 'Voltar', discussions_path, class: "waves-effect waves-teal btn-flat" %>

app/views/discussions/show.html.erb
<p>
 <div class="row">
    <div class="col s12 m6">
      <div class="card blue-grey darken-1">
        <div class="card-content white-text">
          <span class="card-title"> <%= @discussion.headline %> </span>
           <div class="card-action">
            <p><%= @discussion.content %></p>
            <br>
            <% if @discussion.url_image? %>
             <img <%= image_tag @discussion.url_image, width:100, heidth:200 %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="left"><%= @discussion.comments.count %>   Comentário(s) </div>
  <br>
  
  <%= render @discussion.comments %> 

  <h4> Responder ao Tópico </h4>
  
  <%= render 'comments/form' %>


<%= link_to 'Editar', edit_discussion_path(@discussion), class: "waves-effect waves-teal btn-flat" %> |
<%= link_to 'Home', discussions_path, class: "waves-effect waves-teal btn-flat" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <title>Forum News</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar-fixed">
      <nav class="blue darken-2">
        <div class="nav-wrapper">
          <div class="container">
            <div class="container">
            <a href="#!" class="brand-logo">Forun</a>
              <%= link_to  "Forum News!", root_path, class: "brand-logo" %>
              <ul id="nav-mobile" class="right hide-on-med-and-down">
                <a>É verdade essas afirmações</a>
             </ul>
             <ul class="right hide-on-med-and-down">
             <i class="material-icons">question_answer</i>
          </ul>
        </div>
      </nav>
    </div>
  </div>
  <ul class="brand-logo center">
   <i class="material-icons">warning</i>
   <a>Por questões de versão do software. Atualize as páginas que contenham 'Área de Texto' para aparecer a caixinha de Emojis.</a>
  </ul>
  
    <p class="navbar-text float-right">
      <% if user_signed_in? %>
       Logado como: <strong><%= current_user.email %></strong>.
       <%= link_to "Sair", destroy_user_session_path, method: :delete,  :class => 'navbar-link'  %>
      <% else %>  
       <%= link_to "Registrar-se", new_user_registration_path, :class => 'navbar-link'  %> |
       <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </p>
  

    <div class="container">
      
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>
      
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %> 
      
      <%= yield %>
    </div>
  </body>
</html>